# Generated by Django 4.0.5 on 2022-07-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
